### ISSUE TITLE
Typo step2.py

### ISSUE THREAD

**Issue by DecayMehls** [d120/beautiful-tucan#10]
Traceback (most recent call last):
  File "step2.py", line 466, in <module>
    if __name__ == "__main__": main()
  File "step2.py", line 125, in main
    utils.file_write(folder + "/main.js", code_tmpl)
UnboundLocalError: local variable 'code_tmpl' referenced before assignment

Line 83:   code_tpml = utils.file_read("dist/main.js")
should be   code_tmpl = utils.file_read("dist/main.js")

**Comment by miterion** [comment]
Already fixed on master (see 99d1010a3f1b18fd0361ae980f2f22c8904e2076)

**Comment by DecayMehls** [comment]
Ahh just copied the clone link from the readme without double checkin.
You still have the link to drcicero git in the readme and not to your fork.
