### ISSUE TITLE
Why is the output (gh-pages/*) part of the repo?

### ISSUE THREAD

**Issue by drcicero** [d120/beautiful-tucan#2]
Hi guys! I saw https://github.com/d120/beautiful-tucan/commit/a6344c73633bf7249176be92f19509aaac1ab239 added the output of the script (the directory gh-pages/*) to the repo. I am a little confused. Clearly it is redundant to the code, because it can always be regenerated.

Besides I was always a little cautious about putting the data in the repo, because I am not sure, whether it is sensible to store the tucan event data in git history for all eternity, DSGVO data minimization principle and all. Previously, I had it in a separate branch "gh-pages", so i could at at least delete the branch to get rid of it, that's not possible if you mix it with the rest of the code. Eventually, I deleted the branch and switched to copy the output from my laptop via ssh to a static file server.

What is you plan?

**Comment by Miterion** [comment]
Our current strategy is to deploy out of this repository, therefore we decided to push the generated content into the same repo.

As far as I know there is no "secret data" uploaded since most of these things should be accessible through the tucan web page. Since anybody can scrape that and save it for all eternity it does not matter if we publish it in here, although this is only my personal opinion.

**Comment by drcicero** [comment]
(Note public != eternal. For example me crossing a street in public is public, but I would not be ok with it being eternal recorded. Anyway, I noticed that tucan serves old semester info back to 2011, so serving old copies is probably no issue. :smiley: )

Do you mean you run it locally and push to git, then there is a commit hook or something like that that makes server download the files and serve them? Or did you point the domain / redirect the page to github.io serving the gh-pages folder?

If I understand you correctly, you currently have to do a commit every time you want to update the site. The code needs to run more often than the code changes though. That is, because the data in tucan surprisingly changes even after the official semester course list publication date -- I think this semester I notices 3 new courses appearing from the date of the initial publication of the semester course list to date of the first course. Also, there is the thing with rescheduled dates and shifting rooms.

Can we at least push the output into a different branch? E.g. previously I did something similar to I did something similar to the following: Create a branch called gh-pages. git clone the repo twice, switch one to master one to gh-pages; then to update:

~~~sh
cd beautiful-tucan-master                 # goto code branch
git pull                                  #  update code to newest master
sh make.sh                                #  run code
mv gh-pages/* ../beautiful-tucan-gh-pages #  copy output to other branch
cd ../beautiful-tucan-gh-pages            # goto data branch
git commit -a today run                   #  commit new data
git push                                  #  push new data
~~~

**Comment by Miterion** [comment]
Good thinking, I will change our script to use an extra branch.
