### ISSUE TITLE
IT-Sicherheit Pflichtkurse fehlen

### ISSUE THREAD

**Issue by shoeper** [d120/beautiful-tucan#6]
Der Kurs "Einführung in die Kryptographie" fehlt. Eventuell fehlen auch andere Pflichtveranstaltungen.

**Comment by drcicero** [comment]
Dieser Kurs? https://www.d120.de/semesterplan/BScInformatik2015.html#20-00-0085;e30= ?

Der taucht auch in Tucan unter VV / Bachelor / Pflicht nicht auf:
https://www.tucan.tu-darmstadt.de/scripts/mgrqispi.dll?APPNAME=CampusNet&PRGNAME=ACTION&ARGUMENTS=-Ag53pj4eEjRjX~Du24ilV~qetl2UBRWNvPXwjWy~gS4UgI2NkKdzRj1552gyE-tQ5qMebiVYsU40jFM~5rj6KpMT-od7ix5tHEFoTY2ASjFJkr8kvBD1rYIre6UYfeCNjp4Lx21Ko9TNNHkw1Vadm7fruVepndoMFDsK7LhLmWQ7gjmfrcQA46IOOwgbThFKTVkLkAa39xVTrdSU_.

**Comment by shoeper** [comment]
Sorry, ich war sehr unpräzise.

Es geht um die Master Ansicht für IT-Sicherheit. Dort fehlt der Kurs komplett obwohl es sich um eine Pflichtveranstaltung handelt.

https://www.d120.de/semesterplan/MScITSicherheit2015.html#;e30=

**Comment by drcicero** [comment]
Ok, ich habe die Modul-Ids im Studienplan IT-Sicherheit nachgeschlagen,
und für MSc IT-Sicherheit folgende drei (manuelle :sob:) Ergänzungen hinzugefügt:

Test: https://www.student.informatik.tu-darmstadt.de/~dr85nixo/beautiful-tucan/MScITSicherheit2015.html#20-00-0085;e30=

~~~python
  result["M.Sc. IT-Sicherheit (2015)"]["20-00-0085"] = [
    "Pflichtveranstaltung", "Einführung in die Kryptographie"]
  result["M.Sc. IT-Sicherheit (2015)"]["20-00-0219"] = [
    "Pflichtveranstaltung", "IT-Sicherheit"]
  result["M.Sc. IT-Sicherheit (2015)"]["20-00-0581"] = [
    "Pflichtveranstaltung", "Embedded System Security"]
  # und ein paar andere Zeilen angepasst
~~~

**Comment by shoeper** [comment]
Danke :)
