### ISSUE TITLE
Mathe-Pflichtangebote fehlen bzw. sind wenig nachvollziehbar einsortiert

### ISSUE THREAD

**Issue by roessling** [d120/beautiful-tucan#9]
Konkret ist Mathe I und Treffpunkt zur Mathe I im Bereich C ("Katalog Logik"), AfSE habe ich gar nicht gefunden. Beide sollten möglichst bei der "Pflichtlehre", auch wenn sie Angebote des FB 4 sind.

**Comment by drcicero** [comment]
Danke für das Feedback!

Mathe macht immer Probleme, da es in Tucan-VV nicht unter Informatik steht :(.

Ich habe mal alle FB04 Kurse (sind gerade Mathe1, Mathetreff) im Bachelor nach oben geschoben. 

Das Fach AfSE wird aber nicht mal über Inferno dem BSc Informatik 2015 zugeordnet (http://inferno.dekanat.informatik.tu-darmstadt.de/pp/plans/modules/04-00-0120 --> unten bei Studienordnung).

Also hab ich es manuel über die Modul-Id eingefügt:

~~~python
    result["B.Sc. Informatik (2015)"]["04-00-0120"] = [
      "0. Mathe und Pflichtveranstaltungen", "Automaten, formale Sprachen und Entscheidbarkeit"]
~~~

Test: https://www.student.informatik.tu-darmstadt.de/~dr85nixo/beautiful-tucan/BScInformatik2015.html#04-00-0118,04-00-0120,04-00-0301;e30=

**Comment by roessling** [comment]
Super, vielen Dank!

Viele Grüße und ein schönes Wochenende,

Guido
Am 13. Okt. 2019, 00:34 +0200 schrieb drcicero <notifications@github.com>:
